_wandb:
    value:
        cli_version: 0.21.1
        e:
            dnnb69sxkdf5i3hk7adyfs2d5i2u7rqm:
                codePath: wandb/sample.py
                codePathLocal: sample.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "126227054592"
                        used: "90397741056"
                email: siddhartha.gairola18@gmail.com
                executable: /BS/dnn_interpretablity_robustness_representation_learning_2/work/libs/miniforge3/envs/openmmlab_mmdet_xx/bin/python
                git:
                    commit: 0424270ffd55801a3e4ecb22b22e8668677bfbe5
                    remote: https://github.com/sidgairo18/cvml_engineering_gym.git
                gpu: NVIDIA L40S
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-a4e5b39e-b926-b638-e086-f409a16d0539
                host: gpu17-l40-04
                memory:
                    total: "404295909376"
                os: Linux-6.6.88.1.amd64-smp-x86_64-with-glibc2.17
                program: sample.py
                python: CPython 3.8.20
                root: /BS/generative_modelling_for_image_understanding/work/my_projects/github_repos/cvml_engineering_gym/wandb
                slurm:
                    cluster_name: infcluster
                    conf: /var/lib/slurm/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00500050
                    cpu_bind_list: "0x00500050"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "4"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: gpu17_d2
                    job_cpus_per_node: "4"
                    job_gid: "12000"
                    job_id: "44330103"
                    job_name: bash
                    job_nodelist: gpu17-l40-04
                    job_num_nodes: "1"
                    job_partition: gpu17
                    job_qos: gpu17_interactive
                    job_uid: "24176"
                    job_user: sgairola
                    jobid: "44330103"
                    launch_node_ipaddr: 139.19.6.19
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu17-l40-04
                    nprocs: "1"
                    ntasks: "1"
                    procid: "0"
                    pty_port: "34741"
                    pty_win_col: "126"
                    pty_win_row: "37"
                    script_context: prolog_task
                    srun_comm_host: 139.19.6.19
                    srun_comm_port: "35439"
                    step_gpus: "0"
                    step_id: "0"
                    step_launcher_port: "35439"
                    step_nodelist: gpu17-l40-04
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /BS/generative_modelling_for_image_understanding/work/my_projects/github_repos/mmdetection
                    submit_host: slurm-submit-0
                    task_pid: "303134"
                    tasks_per_node: "1"
                    topology_addr: gpu17-l40-04
                    topology_addr_pattern: node
                    umask: "0022"
                    working_cluster: infcluster:slurm-control:6817:9728:109
                startedAt: "2025-08-23T01:54:47.008325Z"
                writerId: dnnb69sxkdf5i3hk7adyfs2d5i2u7rqm
        m: []
        python_version: 3.8.20
        t:
            "3":
                - 2
                - 16
            "4": 3.8.20
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
